// The upgrade pictures (docs/04, docs/13): one 16x16 badge per upgrade, so a level-up card, the camp, the merchant and the HUD can
// show what a boon IS at a glance. Each is a round enamel badge (a themed disc with a lead outline and a lit rim) with a 10x10
// symbol drawn on it in the Glass palette. Procedural text bitmaps like the rest of the UI kit, packed into the atlas at startup
// (uiArt.ts), so a drawn replacement can slot in under the same `boon-<id>` name. A symbol marked `mirror` gives its left five
// columns and is reflected.
export const BOON_SIZE = 16;
const SYM = 10;

export type Theme = 'crimson' | 'lapis' | 'green' | 'ink' | 'earth';

export interface BoonSymbol { theme: Theme; rows: readonly string[]; mirror?: boolean }

/** Disc colours: [rim, fill] as palette keys (uiArt's Glass palette). */
const THEMES: Record<Theme, [string, string]> = {
  crimson: ['R', 'r'], lapis: ['b', 'a'], green: ['m', 'n'], ink: ['z', 'k'], earth: ['O', 'o'],
};

export const BOON_SYMBOLS: Readonly<Record<string, BoonSymbol>> = {
  heavy: { theme: 'crimson', rows: [
    '..........',
    '.XXXXXXXX.',
    '.XWWWWWWz.',
    '.zzzzzzzz.',
    '....tO....',
    '....tO....',
    '....tO....',
    '....tO....',
    '....tO....',
    '...kkkk...',
  ] },
  thick: { theme: 'lapis', rows: [
    '.zzzzzzzz.',
    'zXXXGGZZZz',
    'zXXXGGZZZz',
    'zGGGGGGGGz',
    'zXXXGGZZZz',
    '.zXXGGZZz.',
    '.zXXGGZZz.',
    '..zXGGZz..',
    '...zGGz...',
    '....zz....',
  ] },
  swift: { theme: 'green', rows: [
    '..........',
    '...OOO....',
    '...OtO....',
    'WW.OtO....',
    'WWWOtOO...',
    '.WWOtttOO.',
    '...OttttO.',
    '...tttttt.',
    '...kkkkkk.',
    '..........',
  ] },
  windfall: { theme: 'earth', rows: [
    '..........',
    '...GGGG...',
    '..GYYYYG..',
    '.GYYggYYG.',
    '.GYgYYgYG.',
    '.GYgYYgYG.',
    '.GYYggYYG.',
    '..GGGGGG..',
    '...gggg...',
    '..........',
  ] },
  wind: { theme: 'green', rows: [
    '..........',
    '.RRR..RRR.',
    'RqqRRRRRRR',
    'RqRRRRRRRR',
    'RRRRRRRRRR',
    '.RRRRRRRR.',
    '..RRRRRR..',
    '...RRRR...',
    '....RR....',
    '..........',
  ] },
  spark: { theme: 'lapis', rows: [
    '......YYY.',
    '.....YYY..',
    '....YYY...',
    '...YYYYYY.',
    '.....YYY..',
    '....YYY...',
    '...YYY....',
    '..YYY.....',
    '.YY.......',
    '..........',
  ] },
  lust: { theme: 'ink', rows: [
    '....q.....',
    '....Rq....',
    '...RRRq...',
    '...RRRR...',
    '..RRRRRR..',
    '.RqRRRRRR.',
    '.RqRRRRRR.',
    '.RRRRRRRR.',
    '..RRRRRR..',
    '...rrrr...',
  ] },
  gift: { theme: 'earth', rows: [
    '....R.....',
    '.R..R..R..',
    '..R.Y.R...',
    '...RYR....',
    'RRRYWYRRR.',
    '...RYR....',
    '..R.Y.R...',
    '.R..R..R..',
    '....R.....',
    '..........',
  ] },
  last: { theme: 'ink', rows: [
    '..........',
    '.RRR..RRR.',
    'RqqRkRRRRR',
    'RqRRkRRRRR',
    'RRRkkRRRRR',
    '.RRkRRRRR.',
    '..RRkRRR..',
    '...RkRR...',
    '....kR....',
    '..........',
  ] },
  pound: { theme: 'crimson', rows: [
    '....YY....',
    '....YY....',
    '....YY....',
    '..YYYYYY..',
    '...YYYY...',
    '....YY....',
    '.XXXXXXXX.',
    'XzzXXXXzzX',
    '..........',
    '..........',
  ] },
  tithe: { theme: 'ink', rows: [
    '.GGGGGGGG.',
    '.GRRRRRRG.',
    '..GRRRRG..',
    '..GGGGGG..',
    '...GGGG...',
    '....GG....',
    '....GG....',
    '...GGGG...',
    '..GGGGGG..',
    '..........',
  ] },
  exec: { theme: 'crimson', rows: [
    '..XXXXXX..',
    '.XXXXXXXX.',
    'XXXXXXXXXX',
    'XkkkXXkkkX',
    'XkkkXXkkkX',
    'XXXXkkXXXX',
    '.XXXXXXXX.',
    '..XkXXkX..',
    '..XXXXXX..',
    '...zzzz...',
  ] },
  rift: { theme: 'earth', rows: [
    'Y...Y...Y.',
    '.Y..Y..Y..',
    '..Y.Y.Y...',
    '...YYY....',
    '....Y.....',
    '....Y.....',
    '....Y.....',
    '....Y.....',
    '....R.....',
    '..........',
  ] },
  recoil: { theme: 'lapis', rows: [
    '..........',
    '...zzzz...',
    '..zXXXXz..',
    '.GzXXXXzG.',
    'G.zXXXXz.G',
    '.GzXXXXzG.',
    '..zXXXXz..',
    '...zXXz...',
    '....zz....',
    '..........',
  ] },
  twin: { theme: 'ink', rows: [
    '..Y....Y..',
    '.YG....GY.',
    '.GYG..GYG.',
    'GGYG..GYGG',
    'GYYG..GYYG',
    'GYYG..GYYG',
    '.GYG..GYG.',
    '..GG..GG..',
    '..........',
    '..........',
  ] },
  echo: { theme: 'ink', rows: [
    '..cccccc..',
    '.c......c.',
    'c..cccc..c',
    'c.c....c.c',
    'c.c.YY.c.c',
    'c.c.YY.c.c',
    'c.c....c.c',
    'c..cccc..c',
    '.c......c.',
    '..cccccc..',
  ] },
  quick: { theme: 'lapis', mirror: true, rows: [
    'GGGGG',
    '.XXXX',
    '..XXX',
    '...XX',
    '....X',
    '....X',
    '...XX',
    '..XXY',
    '.XYYY',
    'GGGGG',
  ] },
  radiance: { theme: 'lapis', rows: [
    '....YY....',
    '.Y..YY..Y.',
    '..Y....Y..',
    '...YYYY...',
    'YY.YWWY.YY',
    'YY.YWWY.YY',
    '...YYYY...',
    '..Y....Y..',
    '.Y..YY..Y.',
    '....YY....',
  ] },
  wrath: { theme: 'lapis', rows: [
    '....YY....',
    '....YY....',
    '..YYYYYY..',
    '..YYYYYY..',
    '....YY....',
    '....YY....',
    '....YY....',
    '....YY....',
    '....RR....',
    '....RR....',
  ] },
  vigil: { theme: 'lapis', rows: [
    '....Y.....',
    '...YWY....',
    '...YWY....',
    '....Y.....',
    '...WWWW...',
    '...WXXW...',
    '...WXXW...',
    '...WXXW...',
    '..GGGGGG..',
    '..GGGGGG..',
  ] },
  dance: { theme: 'ink', rows: [
    '...WWWW...',
    '..WWwww...',
    '.WWW...Y..',
    '.WWW......',
    '.WWW...Y..',
    '.WWW......',
    '..WWw.....',
    '...WWWWW..',
    '..........',
    '..........',
  ] },
  keen: { theme: 'crimson', rows: [
    '........XX',
    '.......XXz',
    '......XXz.',
    '.....XXz..',
    '....XXz...',
    '..G.Xz....',
    '...GG.....',
    '..tGG.....',
    '.tO.......',
    '.O........',
  ] },
  pick: { theme: 'green', rows: [
    '..Y.GG.Y..',
    '...GGGG...',
    '..tOOOOt..',
    '.tOOOOOOt.',
    '.OOOGGOOO.',
    '.OOGYYGOO.',
    '.OOOGGOOO.',
    '..OOOOOO..',
    '..........',
    '..........',
  ] },
  eagle: { theme: 'lapis', mirror: true, rows: [
    '.....',
    '...ww',
    '.wWWW',
    'wWWbb',
    'WWbbk',
    'WWbbk',
    'wWWbb',
    '.wWWW',
    '...ww',
    '.....',
  ] },
  downpour: { theme: 'ink', rows: [
    '.t........',
    '.t........',
    '.t..t.....',
    '.t..t.....',
    'XXX.t...t.',
    '.X..t...t.',
    '...XXX..t.',
    '....X...t.',
    '.......XXX',
    '........X.',
  ] },
  ring: { theme: 'earth', rows: [
    '...tXXt...',
    '.tt....tt.',
    '.t......t.',
    't...YY...t',
    'X...YY...X',
    'X...YY...X',
    't........t',
    '.t......t.',
    '.tt....tt.',
    '...tXXt...',
  ] },
  banner: { theme: 'lapis', rows: [
    '.o........',
    '.oRRRRRR..',
    '.oRqqRRRR.',
    '.oRRRRRR..',
    '.oRRRRR...',
    '.oRRR.....',
    '.o........',
    '.o........',
    '.o........',
    'ooo.......',
  ] },
  ward: { theme: 'green', rows: [
    '...cccc...',
    '.cc....cc.',
    '.c..WW..c.',
    'c..WWWW..c',
    'c..WWWW..c',
    'c...WW...c',
    '.c..WW..c.',
    '.cc....cc.',
    '...cccc...',
    '..........',
  ] },
  martyr: { theme: 'ink', rows: [
    '...GGGG...',
    '..G....G..',
    '...GGGG...',
    '.RRR..RRR.',
    'RqRRRRRRRR',
    'RRRRRRRRRR',
    '.RRRRRRRR.',
    '..RRRRRR..',
    '...RRRR...',
    '....RR....',
  ] },
  rally: { theme: 'earth', rows: [
    '..........',
    '.......YY.',
    '......YYYY',
    '.....YYYYY',
    '...GGGGGY.',
    '..GGGGGG..',
    '.GGGg.....',
    'GGg.......',
    'Gg........',
    '..........',
  ] },
  glass: { theme: 'ink', rows: [
    '..cccccc..',
    '.cWWccccc.',
    'cWWcccckbc',
    'cWckccbbbc',
    '.ccckcbbc.',
    '..ccckbc..',
    '...cckc...',
    '....bk....',
    '..........',
    '..........',
  ] },
  phoenix: { theme: 'crimson', rows: [
    'Y........Y',
    'RY..YY..YR',
    'RRY.YY.YRR',
    '.RRYYYYRR.',
    '..RYYYYR..',
    '...RYYR...',
    '....YY....',
    '...YRRY...',
    '..YR..RY..',
    '.Y......Y.',
  ] },
  frenzy: { theme: 'crimson', rows: [
    'Z.....XXX.',
    '.Z...XXXz.',
    'Z...XXXz..',
    '...XXXz...',
    '..GXXz....',
    '.GG.z.....',
    'GG........',
    '..........',
    '..........',
    '..........',
  ] },
  tempest: { theme: 'lapis', rows: [
    '.....YY...',
    '....YY....',
    '...YY..W..',
    '..YYYYYY..',
    '.....YY...',
    '....YY..W.',
    '...YY.....',
    '..YY..W...',
    '..Y.......',
    '..........',
  ] },
  bloodmoon: { theme: 'crimson', rows: [
    '...WWWW...',
    '..WWo.....',
    '.WWo......',
    '.WW.......',
    '.WW...R...',
    '.WWo.RRR..',
    '..WWWRRR..',
    '...WWWR...',
    '..........',
    '..........',
  ] },
  undying: { theme: 'green', rows: [
    '....YY....',
    '...YYYY...',
    '..YYYYYY..',
    '..YYWWYY..',
    '..YYWWYY..',
    '..YYYYYY..',
    '...YYYY...',
    '....YY....',
    '...gggg...',
    '..........',
  ] },
  wildfire: { theme: 'crimson', rows: [
    '.....R....',
    '....RRR...',
    '...RRYR...',
    'R.RRYYRR.R',
    'RRRRYYYRRR',
    '.RRYYYYRR.',
    '..RRYYRR..',
    '...RRRR...',
    '..........',
    '..........',
  ] },
  rallycry: { theme: 'lapis', rows: [
    '..........',
    '.W......W.',
    '..W.YY.W..',
    '...YYYY...',
    'WW.YYYY.WW',
    '...YYYY...',
    '..W.YY.W..',
    '.W..tt..W.',
    '....tt....',
    '..........',
  ] },
  bsize: { theme: 'lapis', rows: [
    'YYY....YYY',
    'YY......YY',
    'Y........Y',
    '...XXXX...',
    '...XXXX...',
    '...XXXX...',
    '...XXXX...',
    'Y........Y',
    'YY......YY',
    'YYY....YYY',
  ] },
  bcount: { theme: 'lapis', rows: [
    'Y...YY...Y',
    '.Y..YY..Y.',
    '..Y.YY.Y..',
    '...YYYY...',
    '....YY....',
    '....YY....',
    '...XXXX...',
    '..XXXXXX..',
    '...XXXX...',
    '..........',
  ] },
  bspeed: { theme: 'lapis', rows: [
    '..........',
    '.....Y....',
    '......Y...',
    'ZZZ....Y..',
    'XXXXXXXXY.',
    'XXXXXXXXY.',
    'ZZZ....Y..',
    '......Y...',
    '.....Y....',
    '..........',
  ] },
  bpower: { theme: 'lapis', rows: [
    '....YY....',
    '...YYYY...',
    '..YYYYYY..',
    '.YYYYYYYY.',
    '...YYYY...',
    '...YYYY...',
    '...YYYY...',
    '...YYYY...',
    '.GGGGGGGG.',
    '..........',
  ] },
  ssize: { theme: 'crimson', rows: [
    'YYY....YYY',
    'YY......YY',
    'Y........Y',
    '...XXXX...',
    '...XXXX...',
    '...XXXX...',
    '...XXXX...',
    'Y........Y',
    'YY......YY',
    'YYY....YYY',
  ] },
  scount: { theme: 'crimson', rows: [
    'Y...YY...Y',
    '.Y..YY..Y.',
    '..Y.YY.Y..',
    '...YYYY...',
    '....YY....',
    '....YY....',
    '...XXXX...',
    '..XXXXXX..',
    '...XXXX...',
    '..........',
  ] },
  sspeed: { theme: 'crimson', rows: [
    '..........',
    '.....Y....',
    '......Y...',
    'ZZZ....Y..',
    'XXXXXXXXY.',
    'XXXXXXXXY.',
    'ZZZ....Y..',
    '......Y...',
    '.....Y....',
    '..........',
  ] },
  spower: { theme: 'crimson', rows: [
    '....YY....',
    '...YYYY...',
    '..YYYYYY..',
    '.YYYYYYYY.',
    '...YYYY...',
    '...YYYY...',
    '...YYYY...',
    '...YYYY...',
    '.GGGGGGGG.',
    '..........',
  ] },
  nsize: { theme: 'earth', rows: [
    'YYY....YYY',
    'YY......YY',
    'Y........Y',
    '...XXXX...',
    '...XXXX...',
    '...XXXX...',
    '...XXXX...',
    'Y........Y',
    'YY......YY',
    'YYY....YYY',
  ] },
  ncount: { theme: 'earth', rows: [
    'Y...YY...Y',
    '.Y..YY..Y.',
    '..Y.YY.Y..',
    '...YYYY...',
    '....YY....',
    '....YY....',
    '...XXXX...',
    '..XXXXXX..',
    '...XXXX...',
    '..........',
  ] },
  nspeed: { theme: 'earth', rows: [
    '..........',
    '.....Y....',
    '......Y...',
    'ZZZ....Y..',
    'XXXXXXXXY.',
    'XXXXXXXXY.',
    'ZZZ....Y..',
    '......Y...',
    '.....Y....',
    '..........',
  ] },
  npower: { theme: 'earth', rows: [
    '....YY....',
    '...YYYY...',
    '..YYYYYY..',
    '.YYYYYYYY.',
    '...YYYY...',
    '...YYYY...',
    '...YYYY...',
    '...YYYY...',
    '.GGGGGGGG.',
    '..........',
  ] },
  dsize: { theme: 'green', rows: [
    'YYY....YYY',
    'YY......YY',
    'Y........Y',
    '...XXXX...',
    '...XXXX...',
    '...XXXX...',
    '...XXXX...',
    'Y........Y',
    'YY......YY',
    'YYY....YYY',
  ] },
  dcount: { theme: 'green', rows: [
    'Y...YY...Y',
    '.Y..YY..Y.',
    '..Y.YY.Y..',
    '...YYYY...',
    '....YY....',
    '....YY....',
    '...XXXX...',
    '..XXXXXX..',
    '...XXXX...',
    '..........',
  ] },
  dspeed: { theme: 'green', rows: [
    '..........',
    '.....Y....',
    '......Y...',
    'ZZZ....Y..',
    'XXXXXXXXY.',
    'XXXXXXXXY.',
    'ZZZ....Y..',
    '......Y...',
    '.....Y....',
    '..........',
  ] },
  dpower: { theme: 'green', rows: [
    '....YY....',
    '...YYYY...',
    '..YYYYYY..',
    '.YYYYYYYY.',
    '...YYYY...',
    '...YYYY...',
    '...YYYY...',
    '...YYYY...',
    '.GGGGGGGG.',
    '..........',
  ] },
};

type Pix = { w: number; h: number; rgba: Uint8ClampedArray };

/** Build the 16x16 badge for symbol `id` from palette `pal` (palette key -> 0xRRGGBB; 'k' is the lead outline). */
export function boonPixels(sym: BoonSymbol, pal: Readonly<Record<string, number>>): Pix {
  const N = BOON_SIZE;
  const rgba = new Uint8ClampedArray(N * N * 4);
  const put = (x: number, y: number, c: number): void => {
    const o = (y * N + x) * 4;
    rgba[o] = (c >> 16) & 255; rgba[o + 1] = (c >> 8) & 255; rgba[o + 2] = c & 255; rgba[o + 3] = 255;
  };
  const [rim, fill] = THEMES[sym.theme];
  const lead = pal.k, c = (N - 1) / 2;
  for (let y = 0; y < N; y++) for (let x = 0; x < N; x++) {
    const dx = x - c, dy = y - c, d = Math.sqrt(dx * dx + dy * dy);
    if (d > 7.6) continue;
    if (d > 6.7) put(x, y, lead);
    else if (d > 5.6 && dx + dy < 2) put(x, y, pal[rim]); // the lit rim: upper-left only
    else put(x, y, sym.theme === 'ink' ? pal.ink : pal[fill]);
  }
  const rows = sym.rows.map((r) => (sym.mirror ? r + [...r].reverse().join('') : r));
  for (let y = 0; y < SYM; y++) for (let x = 0; x < SYM; x++) {
    const ch = rows[y]?.[x] ?? '.';
    if (ch !== '.' && pal[ch] !== undefined) put(3 + x, 3 + y, pal[ch]);
  }
  return { w: N, h: N, rgba };
}
