// GOBLIN — the horde grunt. Game scale: ~8px of body + outline. Hunched green imp with a long ear, a gold eye, a crimson rag.
// The dagger is baked into every pose (carried low, raised for the windup, swung through the strike); the game adds
// lean/lunge on top. Poses: walk, idle, windup (crouch, mouth open), strike (lunge), hurt (recoil, eye shut), dead.
import { GLASS as G } from '../palette.mjs';
import { rows, weapon, outline } from '../lib.mjs';
import { robedRig } from '../rigs/robed.mjs';

const palette = { l: G.lead, e: G.lead, ...G };
const post = { ink: 'l', all: true };

const head = rows(`
  n.nnn
  nnnnY
  .nnn.
`);
const headOpen = rows(`
  n.nnn
  nnnnY
  .nRR.
`);
const headHurt = rows(`
  n.nnn
  nnnnl
  .nRn.
`);
const robe = rows(`
  .nnn.
  nmmnn
  .nRn.
`);
const shoe = rows(`
  n.
  nn
`);
const dagger = (ang) => weapon({
  angle: ang, len: 5, half: 0.8, grip: 1, holdU: 0,
  mat(u, v, L) {
    if (u >= -1 && u < 0.5) return Math.abs(v) <= 1.4 ? 'G' : null;
    if (u < 0.5 || u > L) return null;
    return Math.abs(v) > (u > L - 1.5 ? 0.3 : 0.8) ? null : (v < 0 ? 'X' : 'Z');
  },
});
const daggerLying = outline(rows(`
  GXXXX
`), 'l');
const parts = { head, headOpen, headHurt, robe, shoe, daggerLying };
const rig = robedRig({
  OX: 5, OY: 2, parts, shoe,
  layout: { robe: [3, 3], head: [4, 0], legB: [3, 6], legF: [5, 6], sleeve: null, hand: [8, 4] },
  prop(o, h, { add, T }) {
    if (o.noweapon) return [];
    const k = add('dg' + (o.ang ?? -50), () => dagger(o.ang ?? -50));
    return [[k, ...T(...h)]];
  },
});
const { pose } = rig;

pose('bare', { noweapon: true });          // standing without the dagger: the source for the corpse
pose('walk0', { bob: 1, lf: 1, lb: -1 });
pose('walk1', { bob: 0 });
pose('walk2', { bob: 1, lf: -1, lb: 1 });
pose('walk3', { bob: 0 });
pose('idle0', { bob: 0 });
pose('idle1', { bob: 1, hy: 0 });
pose('windup0', { ang: -55, lean: -1, bob: 1, hx: -1, lf: -1, lb: 1, headPart: 'headOpen' });
pose('windup1', { ang: -140, lean: -1, bob: 1, hx: -1, hy: 1, lf: -1, lb: 1, headPart: 'headOpen' });
pose('strike0', { ang: -10, lean: 2, hx: 1, lf: 2, lb: -2, headPart: 'headOpen' });
pose('strike1', { ang: 25, lean: 1, bob: 1, lf: 1, lb: -1 });
pose('hurt0', { ang: -20, lean: -1, hx: -1, hy: 1, bob: 1, headPart: 'headHurt' });

export default {
  name: 'goblin', title: 'Goblin', notes: 'Horde grunt. Body poses only; the game draws the dagger.',
  cell: [20, 11], shadow: [8, 3], pivot: [10, 9], palette, post,
  parts, frames: rig.frames,
  // the corpse: the unarmed pose laid on its side, with the dagger dropped beside it (generated by the builder)
  derived: { dead: { fromFrame: 'bare', op: 'lie', after: [['daggerLying', 11, 9]] } },
  anims: {
    walk: { fps: 8, frames: ['walk0', 'walk1', 'walk2', 'walk3'] },
    idle: { fps: 3, frames: ['idle0', 'idle1'] },
    windup: { fps: 1, frames: ['windup0', 'windup1'] },
    strike: { fps: 1, frames: ['strike0', 'strike1'] },
    hurt: { fps: 1, frames: ['hurt0'] },
  },
};
