// ORC — the brute (and the charger). ~13px of body + outline, plus horns. Broad, hunched, brown hide, jutting tusks, one iron
// pauldron, and a horned iron skullcap. The club is baked into every pose; the game adds lean/lunge on top. Poses: walk, idle, windup, strike,
// hurt, and the charge set (paw = rocking back to charge, charge = full gallop, dazed = head-down after the rush).
import { GLASS as G } from '../palette.mjs';
import { rows, weapon, outline } from '../lib.mjs';
import { robedRig } from '../rigs/robed.mjs';

const palette = { l: G.lead, e: G.lead, ...G };
const post = { ink: 'l', all: true };

const head = rows(`
  .ooo..
  oOOOOe
  oOOOOY
  .OWWW.
`);
const headRoar = rows(`
  .ooo..
  oOOOOe
  oOOOOY
  .ORRW.
`);
const headHurt = rows(`
  .ooo..
  oOOOOe
  oOOOOl
  .OWWW.
`);
const headDown = rows(`
  .ooo..
  oOOOOe
  oOOOOl
  .OWWW.
`);
const robe = rows(`
  .ZZZOOO.
  ZZXZOOOO
  ZZZZOOOO
  .OOOtOO.
  .OOOOOO.
  .oRRRRo.
`);
const shoe = rows(`
  .oo
  .oo
  ooo
`);
// an iron skullcap with two long bone horns sweeping up and out: the orc's calling card, readable even in the crowd
const hat = rows(`
  W......W
  Ww....wW
  .wZZZZw.
  ..ZZXZ..
`);
const club = (ang) => weapon({
  angle: ang, len: 9, half: 0.9, grip: 1, holdU: 0,
  mat(u, v, L) {
    if (u >= -1 && u < L - 3) return Math.abs(v) <= 0.6 ? 'g' : null;
    const d = Math.hypot(u - (L - 1.2), v);
    if (d < 2.3) return d < 1.1 ? 'X' : 'z';
    return null;
  },
  // no outline of its own: the builder's edge pass already inks the whole silhouette, and a second ring made it 2px thick
});
const clubLying = outline(rows(`
  gggggzz
`), 'l');
const parts = { head, headRoar, headHurt, headDown, robe, shoe, hat, clubLying };
const rig = robedRig({
  OX: 9, OY: 5, parts, shoe,
  layout: { robe: [3, 4], head: [4, 0], hat: [3, -3], legB: [4, 10], legF: [7, 10], sleeve: null, hand: [11, 5] },
  prop(o, h, { add, T }) {
    if (o.noweapon) return [];
    const k = add('cb' + (o.ang ?? -65), () => club(o.ang ?? -65));
    return [[k, ...T(...h)]];
  },
});
const { pose } = rig;
pose('bare', { noweapon: true });          // standing without the club: the source for the corpse
pose('walk0', { bob: 1, lf: 1, lb: -1, lbl: 0 });
pose('walk1', { bob: 0, lf: 0, lb: 0 });
pose('walk2', { bob: 1, lf: -1, lb: 1 });
pose('walk3', { bob: 0, lf: 0, lb: 0 });
pose('idle0', { bob: 0 });
pose('idle1', { bob: 1 });
pose('windup0', { ang: -70, lean: -1, bob: 1, hx: -1, lf: -1, lb: 1, headPart: 'headRoar' });
pose('windup1', { ang: -150, lean: -2, bob: 1, hx: -1, hy: 1, lf: -1, lb: 1, headPart: 'headRoar' });
pose('strike0', { ang: -10, lean: 3, bob: 1, hx: 1, lf: 2, lb: -2, headPart: 'headRoar' });
pose('strike1', { ang: 28, lean: 2, bob: 1, lf: 1, lb: -1 });
pose('hurt0', { ang: -30, lean: -1, hx: -1, hy: 1, bob: 1, headPart: 'headHurt' });
// charge: rock back and stomp (paw), then a head-down gallop with the horns levelled, then daze
pose('paw0', { ang: -45, lean: -1, bob: 2, hx: -1, hy: 1, lf: -1, lb: 1, lfl: 1, headPart: 'headRoar' });
pose('paw1', { ang: -60, lean: -2, bob: 1, hx: -1, hy: 1, lf: 0, lb: 1, headPart: 'headRoar' });
pose('charge0', { ang: 15, lean: 3, bob: 2, hx: 2, hy: 2, lf: 2, lb: -2, headPart: 'headRoar' });
pose('charge1', { ang: 15, lean: 3, bob: 1, hx: 2, hy: 2, lf: -2, lb: 2, headPart: 'headRoar' });
pose('dazed0', { ang: 20, lean: 1, bob: 2, hx: 1, hy: 3, lf: 1, lb: -1, headPart: 'headDown' });
pose('dazed1', { ang: 20, lean: -1, bob: 2, hx: 0, hy: 3, lf: -1, lb: 1, headPart: 'headDown' });

export default {
  name: 'orc', title: 'Orc', notes: 'Horned brute / charger. Body poses only; the game draws the club.',
  cell: [34, 19], shadow: [14, 4], pivot: [17, 17], palette, post,
  parts, frames: rig.frames,
  // the corpse: the first walk frame laid on its side (generated by the builder, so it always matches the sprite)
  derived: { dead: { fromFrame: 'bare', op: 'lie', after: [['clubLying', 14, 17]] } },
  anims: {
    walk: { fps: 8, frames: ['walk0', 'walk1', 'walk2', 'walk3'] },
    idle: { fps: 3, frames: ['idle0', 'idle1'] },
    windup: { fps: 1, frames: ['windup0', 'windup1'] },
    strike: { fps: 1, frames: ['strike0', 'strike1'] },
    hurt: { fps: 1, frames: ['hurt0'] },
    paw: { fps: 6, frames: ['paw0', 'paw1'] },
    charge: { fps: 12, frames: ['charge0', 'charge1'] },
    dazed: { fps: 4, frames: ['dazed0', 'dazed1'] },
  },
};
